import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const templateStyle = {
  maxWidth: "80rem",
  marginLeft: "auto",
  marginRight: "auto",
};

export function Loading() {
  return <span className="loading loading-ball loading-lg"></span>;
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={templateStyle} className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
